### ISSUE TITLE
Slide to refresh and calling the update script. 

### ISSUE THREAD

**Issue by aminecmi** [yDelouis/selfoss-android#47]
I'm not sure if it is the case, but it would be great if the update script was called when sliding to refresh.

**Comment by yDelouis** [comment]
Slide to refresh just sync the app with the server but does not call the update script. I don't think we should call the update script when sliding to refresh because it can be very long.
But we could another button to call this script, in the left menu for example.

**Comment by aminecmi** [comment]
Yeah that would be really great :)
